# Evaluación Parcial 1
## Exploración y Preprocesamiento de Datos

**Asignatura:** Machine Learning - TLY1101  
**Caso:** Predicción de Abandono de Clientes - Telco Customer Churn  

### Contexto

Una empresa de telecomunicaciones busca comprender los factores asociados al abandono de sus clientes con el propósito de apoyar futuras estrategias de retención.

El objetivo de esta etapa es realizar la exploración y el preprocesamiento del conjunto de datos **Telco Customer Churn**, preparando la información para posteriormente utilizarla en modelos de Machine Learning.

La variable objetivo del problema es **Churn**, que indica si un cliente abandonó o no la compañía.

### Importación de librerías

*Se importan las bibliotecas necesarias para realizar la exploración, limpieza, transformación y preprocesamiento del conjunto de datos.*

In [ ]:
#imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

In [11]:
#cargamos la bd
df=pd.read_csv('Telco_Customer_Churn_Dataset.csv')
print("Cantidad de filas:", df.shape[0])
print("Cantidad de columnas:", df.shape[1])
print(df.info())
df.head(2)

Cantidad de filas: 7043
Cantidad de columnas: 21
<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB
None

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No

In [13]:
df.describe()
df.describe(include="object")

/tmp/ipykernel_11110/905123212.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,customerID,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges,Churn
count,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043
unique,7043,2,2,2,2,3,3,3,3,3,3,3,3,3,2,4,6531,2
top,7590-VHVEG,Male,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,20.2,No
freq,1,3555,3641,4933,6361,3390,3096,3498,3088,3095,3473,2810,2785,3875,4171,2365,11,5174

In [14]:
#revisar datos duplicados
df.duplicated().sum()

np.int64(0)

### Revisión de registros duplicados

No se hallaron registros duplicados en el conjunto de datos. Por ende no es necesario eliminar observaciones por duplicidad.

### Conclusión de la exploración inicial

El conjunto de datos contiene 7.043 registros y 21 variables. La variable objetivo es `Churn`, correspondiente a un problema de clasificación binaria.

Durante la revisión inicial se identificaron variables numéricas y categóricas. Además, se observó que `TotalCharges` está almacenada como tipo `object`, a pesar de representar un valor monetario, por lo que será necesario convertirla a una variable numérica antes de continuar con el análisis.

No se detectaron registros completamente duplicados.